#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
version: "3.8"
name: immich

services:
  immich-server:
    networks:
      - internal
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.immich.entrypoints=web"
      - "traefik.http.routers.immich.rule=Host(`photos.gyurus.hu`)"
      - "traefik.http.services.immich.loadbalancer.server.port=2283"
      - "traefik.http.middlewares.immich-headers.headers.customrequestheaders.X-Forwarded-Proto=http"
      - "traefik.http.routers.immich.middlewares=immich-headers"
    ports:
      - "2283:2283"
    env_file:
      - path: .env
        required: true
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    environment:
      - IMMICH_MACHINE_LEARNING_URL=http://immich_machine_learning:3003
      - UPLOAD_LOCATION=/mnt/hdd/library
      - THUMB_LOCATION=/mnt/hdd/immich-thumbs
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION:-/mnt/hdd/library}:/data
      - /etc/localtime:/etc/localtime:ro
      - ${THUMB_LOCATION:-/mnt/hdd/immich-thumbs}:/data/thumbs
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 4g
  redis:
    networks:
      - internal
    env_file:
      - path: .env
        required: true
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512m

  database:
    networks:
      - internal
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:41eacbe83eca995561fe43814fd4891e16e39632806253848efaf04d3c8a8b84
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_DB: ${DB_DATABASE_NAME:-immich}
      POSTGRES_INITDB_ARGS: "--data-checksums"
      DB_DATA_LOCATION: ${DB_DATA_LOCATION:-/mnt/hdd/immich-db}
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      DB_STORAGE_TYPE: "HDD"
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION:-/mnt/hdd/immich-db}:/var/lib/postgresql/data
    shm_size: 256mb
    restart: always

  immich-machine-learning:
    networks:
      - internal
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - /mnt/hdd/immich-model-cache:/cache
    device_cgroup_rules:
      - "c 189:* rmw"
    env_file:
      - .env
    restart: always
    deploy:
      resources:
        limits:
          cpus: "5"
          memory: 5g

  immich-stack:
    networks:
      - internal
    image: ghcr.io/majorfi/immich-stack:latest
    container_name: immich-stack
    env_file: .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  model-cache:
    driver: local
    driver_opts:
      type: none
      device: /mnt/hdd/immich-model-cache
      o: bind

networks:
  internal:
    driver: bridge
  proxy:
    external: true
